Change on 2013-01-08 11:24:29-08:00 	front() should not be called on an empty vector.
Change on 2013-01-09 08:05:46-08:00 by ptab

	Fixing few externally reported issues:
	 * (https://code.google.com/p/supersonic/issues/detail?id=9)
	   Adding compilation flag -gchar-unsigned
	 * (https://code.google.com/p/supersonic/issues/detail?id=8)
	   Adding MMX and SSE flags

	* Extened INSTALL documentation to use "make -j 16" (to speedup build by utilizing more cores)
	* Supersonic does not build with "-g" option by default now (much smaller output files)
	* Supersonic does build with -O3 by default.
	* Checking for BOOST libraries (system, timer) in configure script.

Change on 2013-01-09 08:09:57-08:00 by ptab

	Prepering for external release of supersonic-0.9.3.

Change on 2013-01-09 08:47:09-08:00 by ptab
	  Fixed compilation issues in 32bit mode:
	  error: format specifies type 'int' but the argument has type 'int64' (aka 'long long') [-Werror,-Wformat]

Change on 2013-01-09 10:05:49-08:00

	Adds support for enums to Supersonic.

	This CL does the following:
	* adds core support for the enum type, that consists of (id, value) pairs.
	* adds support for reading enums from proto2 descriptors (in cursor/ext/proto2/ProtoResolver).
	* adds support for parsing enums (by name) from strings.
	* adds support for printing enums to strings (when dumping views for debugging and testing).

	What's missing: any sort of conversion between enums, strings, and integers.

Revision created by MOE tool push_codebase.
MOE_MIGRATION=6097